### PR TITLE
Get ats_uid after packages are installed

### LINKED ISSUE #1397: ORT tries to get ats_uid before installing trafficserver
On first ORT run, trafficserver isn't installed and thus getting `ats_uid` fails and doesn't set all the configuration file with proper permissions.

`my $ats_uid          = getpwnam("ats");` should run after the packages are installed.

```
Thu Oct 12 13:27:23 UTC 2017
ERROR Deleting directories older than 1507210043
INFO Traffic Ops host: https://traffic-ops.tld
INFO Found tm.toolname: Traffic Ops
Use of uninitialized value $ats_uid in concatenation (.) or string at /opt/ort/traffic_ops_ort.pl line 206.
```

Workaround: Run Traffic Ops ORT twice in a row.

### PR DESCRIPTION
**Pull request by smalenfant**
This moves the function that was getting `ats_uid` after packages are installed, or right before processing config files.

Closes #1397

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/472/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/428/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/475/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/430/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/431/

**Comment by dewrich** [comment]
@smalenfant What was the intent of this refactor? I don't see where you are reusing it?

**Comment by smalenfant** [comment]
@dewrich On first time install, ORT would fail setting proper UID for trafficserver files. This is just declaring `ats_uid` as a global so it can be set after trafficserver has been installed during the processing of configuration files.

File: traffic_ops/bin/traffic_ops_ort.pl [hunk 1]
```diff
@@ -1063,6 +1063,7 @@ sub sleep_timer {
 sub process_config_files {
 
 	( $log_level >> $INFO ) && print "\nINFO: ======== Start processing config files ========\n";
+	$ats_uid          = getpwnam("ats");
```
Comment (dewrich) [inline traffic_ops/bin/traffic_ops_ort.pl]: Where does $ats_uid get used next?  Looks like you pulled it into a local variable but I don't see where you refer to it.

Comment (smalenfant) [reply traffic_ops/bin/traffic_ops_ort.pl]: @dewrich It was defined as a global before, which I retained. It is used in function `replace_cfg_file` and in `backup_file` which is called by `process_config_files`.  Should I just locally define $ats_uid in those 2 functions? Looks like it is also redefined locally in `adv_processing_udev`.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/821/
Test FAILed.
