### PR TITLE
[Issue-1642] - return profile type when parameter profiles are fetched plus refactor…

### LINKED ISSUE #1642: Attempt to unlink parameter from DS profile incorrectly shows 0 servers affected
Attempting to unlink an MSO parameter from a profile gives misleading warning message that the parameter is used by 0 servers, which is not true. Servers in this case would be mid tier, which may be a factor in why TO is not corelating.

image

### PR DESCRIPTION
**Pull request by mitchell852**
…ed api into 1 query instead of 2

fixes #1642

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/769/
Test PASSed.

File: traffic_ops/app/lib/API/Profile.pm [hunk 1]
```diff
@@ -90,25 +90,20 @@ sub get_profiles_by_paramId {
 	my $self    	= shift;
 	my $param_id	= $self->param('id');
 
-	my $param_profiles = $self->db->resultset('ProfileParameter')->search( { parameter => $param_id } );
-
-	my $profiles = $self->db->resultset('Profile')->search(
-		{ 'me.id' => { -in => $param_profiles->get_column('profile')->as_query } }
-	);
+	my $param_profiles = $self->db->resultset('ProfileParameter')->search( { parameter => $param_id }, { prefetch => [ 'profile' ] } );
```
Comment (tatemitchell) [inline traffic_ops/app/lib/API/Profile.pm]: are you sure you know what you are doing?
