### PR TITLE
TO go api: explicitly route api/1.2/servers/status to Perl until implemented

### LINKED ISSUE #1429: Traffic Ops golang API api/1.2/servers/status internal error
On current master (2.2),  api/1.2/servers/status fails with a 500 internal error.

### PR DESCRIPTION
**Pull request by dangogh**
fixes #1429

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/532/
Test PASSed.

File: traffic_ops/traffic_ops_golang/routes.go [hunk 1]
```diff
@@ -21,20 +21,28 @@ package main
...
 
+func handlerToFunc(handler http.Handler) http.HandlerFunc {
+	return func(w http.ResponseWriter, r *http.Request) {
+		handler.ServeHTTP(w, r)
+	}
+}
+
 // Routes returns the routes, and a catchall route for when no route matches.
 func Routes(d ServerData) ([]Route, http.Handler, error) {
+	proxyHandlerFunc := handlerToFunc(rootHandler(d))
```
Comment (DylanVolz) [inline traffic_ops/traffic_ops_golang/routes.go]: rootHandler should be assigned to its own variable and reused below.
Currently this creates two separate proxy connection handler instance doubling connections made to Mojolicious (well if half the traffic hit api/1.1/servers/status...)

File: traffic_ops/traffic_ops_golang/routes.go [hunk 2]
```diff
@@ -56,6 +64,8 @@ func Routes(d ServerData) ([]Route, http.Handler, error) {
 		{1.2, http.MethodGet, "regions/{id}$", regionsHandler(d.DB), RegionsPrivLevel, Authenticated, nil},
 		//Servers
 		{1.2, http.MethodGet, `servers(\.json)?$`, serversHandler(d.DB), ServersPrivLevel, Authenticated, nil},
+		// explicitly passed to legacy system until fully implemented
+		{1.2, http.MethodGet, "servers/status$", proxyHandlerFunc, ServersPrivLevel, Authenticated, []Middleware{}},
```
Comment (DylanVolz) [inline traffic_ops/traffic_ops_golang/routes.go]: Since perl TO will be handling authentication and authorization I think this endpoint should `use 0, NoAuth` instead of `ServersPrivLevel, Authenticated`

File: traffic_ops/traffic_ops_golang/routes.go (hunk 1 above)
Comment (dangogh) [reply traffic_ops/traffic_ops_golang/routes.go]: ahh...  yes -- you're right

File: traffic_ops/traffic_ops_golang/routes.go (hunk 2 above)
Comment (dangogh) [reply traffic_ops/traffic_ops_golang/routes.go]: excellent point..

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/534/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/486/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/488/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/535/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/489/
