### PR TITLE
split parameters select query from groupBy to allow where clause to be used

### LINKED ISSUE #1764: parameters endpoint crashes with where clause
The groupBy needs to be separated from the select clause to allow a where clause to be inserted.

### PR DESCRIPTION
**Pull request by DylanVolz**
fixes #1764

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/877/
Test PASSed.

File: traffic_ops/traffic_ops_golang/parameters.go [hunk 1]
```diff
@@ -94,6 +94,7 @@ func getParameters(v url.Values, db *sqlx.DB, privLevel int) ([]tc.Parameter, er
 
 	query, queryValues := dbhelpers.BuildQuery(v, selectParametersQuery(), queryParamsToSQLCols)
 
+	query = query + ParametersGroupBy()
```
Comment (dangogh) [inline traffic_ops/traffic_ops_golang/parameters.go]: that's very Pascal-ish..   why not `query += ...`?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/878/
Test PASSed.
